version: 2.1

workflows:
  deployment:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only:
                - master

jobs:
  build:
    docker:
      - image: circleci/node:gallium
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "package.json" }}
            - v4-dependencies-

      - run:
          command: |
            sudo apt-get update -y
            sudo apt install rsync
            sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v4-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      - run: rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress ./ $USER@$HOST:~/stalkyboi --delete

      - run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USER@$HOST 'pm2 stop stalkyboi && sleep 5 && cd ~/stalkyboi && npm rebuild canvas --update-binary && pm2 start stalkyboi'
